name: Terraform Apply
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false
      - name: Init
        run: terraform init
        working-directory: ./terraform
        id: init
      - name: Apply
        run: terraform apply -var-file=test.tfvars -auto-approve
        working-directory: ./terraform