name: Terraform Plan
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Init
        run: terraform init
        working-directory: ./terraform
        id: init
      - name: Validate
        run: terraform validate -no-color
        working-directory: ./terraform
        id: validate
      - name: Terraform Plan
        run: terraform plan -var-file=test.tfvars -no-color
        working-directory: ./terraform
        id: plan
